language: rust
services:
  - docker
rust:
  - stable
  - beta
  - nightly
before_install: 
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y  openssl libssl-dev libbz2-dev zlib1g-dev ffmpeg yasm
#cache: cargo
script:
  - cargo test --verbose --features partially-static,transcoding-cache
  - cargo test --verbose --no-default-features --features partially-static
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
    - language: node_js
      node_js:
      - "7"
      cache:
        directories:
        - "client/node_modules"
      script:
      - cd client
      - npm install
      - npm run build

before_deploy:
      - if [[ ! -d _static_build ]]; then bash build_static.sh; fi

deploy:
  - provider: script
    script: 
      - bash docker_push.sh
    on:
      branch: master
      tags: true
      rust: stable
  - provider: releases
    api_key:
      secure: NlP+bkwDihtgjWUG0GYT2Ywebon6X1uA6T1ddY/JhmkQ8uoF7+XXQ23jIsu1MOCXHMhzyRlZ2HO5AetNkc6tlBa5qUF3eQNkpYz0CuxQnhjGVqt4UrUBNweqKomavcYxumeiXYtVazpCoSLcRlLAgzaCf1H4KVZSIJTvEIeo1D4+zrFbsG4Fr46M9IRsaQkaVrkYijeaYw3qd5Q1KhdCyeIv5sqQEo7UCDdM+aLryaq7K0FhTAeM84PmYQCYLxWx2zEQ4vl4uHeWkWLeA3kHss/dmhdnZhTVThGLVjtPfzyFIcssy9Buf5B635o05hl2OaETi7AJoG8izD/+gNsd451asTGvuYgn30uKIzy7zrVHXM1D67+rTZoAM48aqC4g99QwIrkiNITI8qlwp7OTjnsgWvyZZgMqGVfdFVvYDAmPggRDrjBFIbApXYDJ6koJvxGb4Vb4qcObNRgxhGeIT78CrX4fsfAoQWHRCj592V3U4hU6xnbRBrf2brfbA+nLKAjJ5cXYQLDciB8EeA7GmSvASJLPBwtsDWiq3IsJQK8RAUiaWoE934YphwPY/WUk0oVRCOgBuh/4YyjGyxUQtknKhXj6+G9D1Tja1z/fiGHnrx32C+CxXAxnZ94LS1AWDX+KE/D3mw4fHbWJVF4jtVxNdskxs6BZMtcxAVDYweY=
    file: _static_build/audioserve_static_v0.9.1.tar.gz
    skip_cleanup: true
    on:
      branch: master
      # tags: true
      rust: stable


