language: rust
rust:
  - stable
  - beta
  - nightly
before_install: 
  - sudo apt-get -qq update
  - sudo apt-get install -y  openssl libssl-dev libtag1-dev libtagc0-dev ffmpeg
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly


