[package]
name = "server"
version = "0.1.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]

[dependencies]
pretty_env_logger = "0.1"
log = "0.4"
hyper = "0.11"
futures = "0.1"
futures-cpupool ="0.1"

