[package]
name = "audioserve"
version = "0.4.3"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]

[dependencies]
pretty_env_logger = "0.2"
log = "0.4"
hyper = "=0.11.25"
futures = "0.1"
mime = "0.3"
mime_guess = "2.0.0-alpha.4"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
clap = "2"
lazy_static = "1.0"
quick-error = "1.2"
url = "1.7"
percent-encoding = "1.0"
num_cpus = "1.8"
ring = "0.12"
data-encoding = "2.1"
regex = "1.0"

# for ssl
tokio-tls = {version="0.1", features=["tokio-proto"], optional=true}
native-tls = {version="0.1", optional=true}
tokio-proto = {version="0.1", optional=true}

[dependencies.taglib]
git = "https://github.com/ebassi/taglib-rust"

[dependencies.simple-thread-pool]
git = "https://github.com/izderadicka/simple-thread-pool.git"

[features]
default = ["tls"]
tls=["tokio-tls", "native-tls", "tokio-proto"]

