[package]
name = "audioserve"
version = "0.1.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]

[dependencies]
pretty_env_logger = "0.1"
log = "0.4"
hyper = "0.11"
futures = "0.1"
futures-cpupool = "0.1"
mime = "0.3"
mime_guess = "2.0.0-alpha.3"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
clap = "2"
#lazy_static = "0.2"
quick-error = "1.2"
url = "1.6"
percent-encoding = "1.0"

[dependencies.taglib]
git = "https://github.com/ebassi/taglib-rust"

