---
listen: "0.0.0.0:3000"
thread_pool:
  num_threads: 8
  queue_size: 100
  keep_alive: ~
base_dirs:
  - /home/ivan/tmp/test_audiobooks/
  - /home/ivan/tmp/audioserve-demo/test_audiobooks_en/
shared_secret: usak
transcoding:
  max_parallel_processes: 8
  max_runtime_hours: 24
  cache:
    root_dir: /tmp/audioserve-cache
    max_size: 1024
    max_files: 1024
    disabled: false
    save_often: false
  low:
    opus-in-ogg:
      bitrate: 32
      compression_level: 5
      cutoff: SuperWideBand
      mono: true
  medium:
    opus-in-ogg:
      bitrate: 48
      compression_level: 8
      cutoff: SuperWideBand
      mono: false
  high:
    opus-in-ogg:
      bitrate: 64
      compression_level: 10
      cutoff: FullBand
      mono: false
token_validity_hours: 8760
secret_file: /home/ivan/.audioserve.secret
client_dir: client/dist
cors: true
ssl: ~
allow_symlinks: false
search_cache: true
disable_folder_download: false
chapters:
  from_duration: 0
  duration: 30
positions_file: /home/ivan/.audioserve-positions
